export const  COURS_LIST_REQUEST='COURS_LIST_REQUEST'
export const COURS_LIST_SUCCESS='COURS_LIST_SUCCESS'
export const COURS_LIST_FAIL='COURS_LIST_FAIL'


export const  COURS_DETAILS_REQUEST='COURS_DETAILS_REQUEST'
export const COURS_DETAILS_SUCCESS='COURS_DETAILS_SUCCESS'
export const COURS_DETAILS_FAIL='COURS_DETAILS_FAIL'
